coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 5%
    patch:
      default:
        target: 80%
        threshold: 5%

comment:
  layout: "diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/*.spec.ts"
  - "**/*.spec.tsx"
  - "**/test-utils.tsx"
  - "**/setup.ts"
  - "**/*.d.ts"
  - "**/dist/**"
  - "**/build/**"
  - "**/coverage/**"
  - "**/node_modules/**"
  - "**/playwright-a11y-webkit.json"
  - "**/playwright-a11y-firefox.json"
  - "**/playwright-a11y-chromium.json"

flag_management:
  default_rules:
    carryforward: true
    statuses:
      - type: project
        target: 80%
      - type: patch
        target: 80%
