// Generated design tokens for Georgia Tech Alumni Association
// Auto-generated from Style Dictionary - DO NOT EDIT MANUALLY

export const GtColorPrimaryGold = '#B3A369'; // Georgia Tech Primary Gold - Tech Gold
export const GtColorPrimaryNavy = '#003057'; // Georgia Tech Primary Navy - Tech Navy
export const GtColorSecondaryBlue = '#0F446C'; // Georgia Tech Secondary Blue
export const GtColorSecondaryGoldLight = '#EAAA00'; // Georgia Tech Light Gold
export const GtColorSecondaryGoldDark = '#857437'; // Georgia Tech Dark Gold
export const GtColorNeutralWhite = '#FFFFFF'; // Pure white
export const GtColorNeutralBlack = '#000000'; // Pure black
export const GtColorNeutralGray100 = '#F8F9FA'; // Lightest gray
export const GtColorNeutralGray200 = '#E9ECEF'; // Light gray
export const GtColorNeutralGray300 = '#DEE2E6'; // Medium light gray
export const GtColorNeutralGray400 = '#CED4DA'; // Medium gray
export const GtColorNeutralGray500 = '#ADB5BD'; // Medium dark gray
export const GtColorNeutralGray600 = '#6C757D'; // Dark gray
export const GtColorNeutralGray700 = '#495057'; // Darker gray
export const GtColorNeutralGray800 = '#343A40'; // Very dark gray
export const GtColorNeutralGray900 = '#212529'; // Darkest gray
export const GtColorSemanticSuccess = '#28A745'; // Success green
export const GtColorSemanticWarning = '#FFC107'; // Warning yellow
export const GtColorSemanticError = '#DC3545'; // Error red
export const GtColorSemanticInfo = '#17A2B8'; // Info blue
export const GtSpacing0 = '0'; // No spacing
export const GtSpacing1 = '0.25rem'; // 4px
export const GtSpacing2 = '0.5rem'; // 8px
export const GtSpacing3 = '0.75rem'; // 12px
export const GtSpacing4 = '1rem'; // 16px
export const GtSpacing5 = '1.25rem'; // 20px
export const GtSpacing6 = '1.5rem'; // 24px
export const GtSpacing8 = '2rem'; // 32px
export const GtSpacing10 = '2.5rem'; // 40px
export const GtSpacing12 = '3rem'; // 48px
export const GtSpacing16 = '4rem'; // 64px
export const GtSpacing20 = '5rem'; // 80px
export const GtSpacing24 = '6rem'; // 96px
export const GtSpacing32 = '8rem'; // 128px
export const GtBorderRadiusNone = '0'; // No border radius
export const GtBorderRadiusSm = '0.125rem'; // 2px
export const GtBorderRadiusBase = '0.25rem'; // 4px
export const GtBorderRadiusMd = '0.375rem'; // 6px
export const GtBorderRadiusLg = '0.5rem'; // 8px
export const GtBorderRadiusXl = '0.75rem'; // 12px
export const GtBorderRadius2xl = '1rem'; // 16px
export const GtBorderRadiusFull = '9999px'; // Fully rounded
export const GtBorderWidth0 = '0'; // No border
export const GtBorderWidth1 = '1px'; // 1px border
export const GtBorderWidth2 = '2px'; // 2px border
export const GtBorderWidth4 = '4px'; // 4px border
export const GtBorderWidth8 = '8px'; // 8px border
export const GtBoxShadowNone = 'none'; // No shadow
export const GtBoxShadowSm = '0 1px 2px 0 rgba(0, 0, 0, 0.05)'; // Small shadow
export const GtBoxShadowBase =
  '0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.06)'; // Base shadow
export const GtBoxShadowMd =
  '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)'; // Medium shadow
export const GtBoxShadowLg =
  '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)'; // Large shadow
export const GtBoxShadowXl =
  '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)'; // Extra large shadow
export const GtFontFamilyPrimary = '"Roboto Slab", Georgia, serif'; // Georgia Tech primary font family for headings
export const GtFontFamilySecondary = '"Source Sans Pro", Arial, sans-serif'; // Georgia Tech secondary font family for body text
export const GtFontFamilyMonospace = '"Roboto Mono", Consolas, monospace'; // Monospace font for code
export const GtFontSizeXs = '0.75rem'; // 12px - Extra small text
export const GtFontSizeSm = '0.875rem'; // 14px - Small text
export const GtFontSizeBase = '1rem'; // 16px - Base font size
export const GtFontSizeLg = '1.125rem'; // 18px - Large text
export const GtFontSizeXl = '1.25rem'; // 20px - Extra large text
export const GtFontSize2xl = '1.5rem'; // 24px - 2X large text
export const GtFontSize3xl = '1.875rem'; // 30px - 3X large text
export const GtFontSize4xl = '2.25rem'; // 36px - 4X large text
export const GtFontSize5xl = '3rem'; // 48px - 5X large text
export const GtFontSize6xl = '3.75rem'; // 60px - 6X large text
export const GtFontWeightLight = '300'; // Light font weight
export const GtFontWeightNormal = '400'; // Normal font weight
export const GtFontWeightMedium = '500'; // Medium font weight
export const GtFontWeightSemibold = '600'; // Semi-bold font weight
export const GtFontWeightBold = '700'; // Bold font weight
export const GtFontWeightExtrabold = '800'; // Extra bold font weight
export const GtFontLineHeightTight = '1.25'; // Tight line height
export const GtFontLineHeightNormal = '1.5'; // Normal line height
export const GtFontLineHeightRelaxed = '1.625'; // Relaxed line height
export const GtFontLineHeightLoose = '2'; // Loose line height
export const ColorNeutralGray600 = '#6c757d';
export const ColorNeutralGray700 = '#495057';
export const ColorNeutralGray800 = '#343a40';
export const ColorNeutralGray900 = '#212529';
export const ColorSemanticSuccess = '#28a745';
export const ColorSemanticWarning = '#ffc107';
export const ColorSemanticError = '#dc3545';
export const ColorSemanticInfo = '#17a2b8';
export const Spacing0 = '0';
export const Spacing1 = '0.25rem';
export const Spacing2 = '0.5rem';
export const Spacing3 = '0.75rem';
export const Spacing4 = '1rem';
export const Spacing5 = '1.25rem';
export const Spacing6 = '1.5rem';
export const Spacing8 = '2rem';
export const Spacing10 = '2.5rem';
export const Spacing12 = '3rem';
export const Spacing16 = '4rem';
export const Spacing20 = '5rem';
export const Spacing24 = '6rem';
export const Spacing32 = '8rem';
export const BorderRadiusNone = '0';
export const BorderRadiusSm = '0.125rem';
export const BorderRadiusBase = '0.25rem';
export const BorderRadiusMd = '0.375rem';
export const BorderRadiusLg = '0.5rem';
export const BorderRadiusXl = '0.75rem';
export const BorderRadius2xl = '1rem';
export const BorderRadiusFull = '9999px';
export const BorderWidth0 = '0';
export const BorderWidth1 = '1px';
export const BorderWidth2 = '2px';
export const BorderWidth4 = '4px';
export const BorderWidth8 = '8px';
export const FontFamilyPrimary = '"Roboto Slab", Georgia, serif';
export const FontFamilySecondary = '"Source Sans Pro", Arial, sans-serif';
export const FontFamilyMonospace = '"Roboto Mono", Consolas, monospace';
export const FontSizeXs = '0.75rem';
export const FontSizeSm = '0.875rem';
export const FontSizeBase = '1rem';
export const FontSizeLg = '1.125rem';
export const FontSizeXl = '1.25rem';
export const FontSize2xl = '1.5rem';
export const FontSize3xl = '1.875rem';
export const FontSize4xl = '2.25rem';
export const FontSize5xl = '3rem';
export const FontSize6xl = '3.75rem';
export const FontWeightLight = '300';
export const FontWeightNormal = '400';
export const FontWeightMedium = '500';
export const FontWeightSemibold = '600';
export const FontWeightBold = '700';
export const FontWeightExtrabold = '800';
export const FontLineHeightTight = '1.25';
export const FontLineHeightNormal = '1.5';
export const FontLineHeightRelaxed = '1.625';
export const FontLineHeightLoose = '2';
