name: 🐛 Bug Report
description: Create a report to help us improve
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: bug-description
    attributes:
      label: 🐛 Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: 📋 Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: ✅ Expected Behavior
      description: A clear and concise description of what you expected to happen
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: ❌ Actual Behavior
      description: A clear and concise description of what actually happened
      placeholder: What actually happened?
    validations:
      required: true

  - type: dropdown
    id: package
    attributes:
      label: 📦 Package
      description: Which package is affected?
      options:
        - "@gtalumni-la/tokens"
        - "@gtalumni-la/react"
        - "@gtalumni-la/typescript"
        - "@gtalumni-la/eslint"
        - "Other"
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: 📝 Package Version
      description: What version of the package are you using?
      placeholder: "0.1.0"
    validations:
      required: true

  - type: dropdown
    id: node-version
    attributes:
      label: 🟢 Node.js Version
      description: What version of Node.js are you running?
      options:
        - "18.x"
        - "20.x"
        - "Other"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: 💻 Operating System
      description: What OS are you using?
      options:
        - "macOS"
        - "Windows"
        - "Linux"
        - "Other"

  - type: dropdown
    id: browser
    attributes:
      label: 🌐 Browser (if applicable)
      description: What browser are you using?
      options:
        - "Chrome"
        - "Firefox"
        - "Safari"
        - "Edge"
        - "Other"
        - "N/A"

  - type: textarea
    id: code-example
    attributes:
      label: 💻 Code Example
      description: Minimal code example that reproduces the issue
      render: tsx
      placeholder: |
        import { Button } from '@gtalumni-la/react';

        function App() {
          return <Button variant="primary">Click me</Button>;
        }

  - type: textarea
    id: additional-context
    attributes:
      label: 🔍 Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information...

  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided a minimal code example that reproduces the issue
          required: true
        - label: I have included all relevant environment information
          required: true
        - label: I have tested this with the latest version of the package
          required: true
