name: Deploy Documentation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build design tokens
        run: pnpm --filter @gtalumni-la/tokens build

      - name: Build React components
        run: pnpm --filter @gtalumni-la/react build

      - name: Build Storybook
        run: pnpm --filter @gtalumni-la/storybook build

      - name: Build VitePress documentation
        run: pnpm --filter @gtalumni-la/docs build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Prepare deployment directory
        run: |
          # Only deploys from main branch to production
          BASE_DIR="dist"
          mkdir -p "$BASE_DIR"
          # Copy VitePress build (main site)
          cp -r apps/docs/.vitepress/dist/* "$BASE_DIR/"
          # Copy Storybook build
          if [ -d "apps/storybook/storybook-static" ]; then
            mkdir -p "$BASE_DIR/storybook"
            cp -r apps/storybook/storybook-static/* "$BASE_DIR/storybook/"
          else
            echo "Error: Storybook build not found at apps/storybook/storybook-static. Check if the Storybook build step completed successfully."
            exit 1
          fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  # Deployment job
  deploy:
    # Only deploy on main branch, not on PRs
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Comment PR with preview URL
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.issue.number;
            const baseUrl = '${{ steps.deployment.outputs.page_url }}';
            const previewUrl = `${baseUrl}pr-preview/${prNumber}/`;
            const storybookUrl = `${previewUrl}storybook/`;

            const comment = `🚀 Preview deployment is ready!

            - Documentation: ${previewUrl}
            - Storybook: ${storybookUrl}`;

            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: comment
            });
