name: Deploy Documentation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build design tokens
        run: pnpm --filter @gtalumni-la/tokens build

      - name: Build React components
        run: pnpm --filter @gtalumni-la/react build

      - name: Build Storybook
        run: pnpm --filter @gtalumni-la/storybook build

      - name: Build VitePress documentation
        run: pnpm --filter @gtalumni-la/docs build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Get current version
        id: version
        run: |
          VERSION="v$(node -p "require('./package.json').version")"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Deploying latest version: $VERSION"

      - name: Prepare deployment directory
        run: |
          mkdir -p dist
          
          # Store current branch before any git operations
          CURRENT_BRANCH=$(git branch --show-current)
          
          # Check out existing gh-pages branch to preserve preview directories
          if git ls-remote --exit-code --heads origin gh-pages > /dev/null 2>&1; then
            echo "Fetching existing gh-pages branch to preserve previews..."
            if ! git fetch origin gh-pages:gh-pages 2>/dev/null; then
              echo "Warning: Failed to fetch gh-pages branch from origin." >&2
            fi
            if ! git checkout gh-pages 2>/dev/null; then
              echo "Warning: Failed to checkout gh-pages branch. Continuing without preserving previews." >&2
            else
              # Copy existing preview directories and manifests
              if [ -d "preview" ]; then
                echo "Preserving existing preview directories..."
                cp -r preview/ dist/
              fi
              if [ -f "previews.json" ]; then
                echo "Preserving existing previews manifest..."
                cp previews.json dist/
              fi
              if [ -f "versions.json" ]; then
                echo "Preserving existing versions manifest..."
                cp versions.json dist/
              fi
              
              # Switch back to original branch content
              git checkout "$CURRENT_BRANCH"
            fi
          fi
          
          # Copy VitePress build (main site) - this will overwrite root files but preserve preview/
          cp -r apps/docs/.vitepress/dist/* dist/
          
          # Copy Storybook build
          if [ -d "apps/storybook/storybook-static" ]; then
            mkdir -p dist/storybook
            cp -r apps/storybook/storybook-static/* dist/storybook/
          else
            echo "Error: Storybook build not found at apps/storybook/storybook-static. Check if the Storybook build step completed successfully."
            exit 1
          fi
          
          # Create or update versions.json if it doesn't exist
          if [ ! -f "dist/versions.json" ]; then
            echo "Creating default versions.json"
            echo '{"current": {"version": "${{ steps.version.outputs.version }}", "path": "/", "label": "${{ steps.version.outputs.version }} (latest)"}, "versions": []}' > dist/versions.json
          fi
          
          # Create default previews.json if it doesn't exist
          if [ ! -f "dist/previews.json" ]; then
            echo "Creating default previews.json"
            echo '{"previews": []}' > dist/previews.json
          fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  # Deployment job
  deploy:
    # Deploy on main branch only (latest version)
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Comment PR with preview URL
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.issue.number;
            const baseUrl = '${{ steps.deployment.outputs.page_url }}';
            const previewUrl = `${baseUrl}pr-preview/${prNumber}/`;
            const storybookUrl = `${previewUrl}storybook/`;

            const comment = `🚀 Preview deployment is ready!

            - Documentation: ${previewUrl}
            - Storybook: ${storybookUrl}`;

            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: comment
            });
